sudo: required
services:
    - docker

before_install:
    - docker build -t jeshocarmel/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jeshocarmel/react-test npm test 

after_success:
    - docker build -t jeshocarmel/multi-client ./client
    - docker build -t jeshocarmel/multi-nginx ./nginx
    - docker build -t jeshocarmel/multi-server ./server
    - docker build -t jeshocarmel/multi-worker ./worker
    
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push jeshocarmel/multi-client
    - docker push jeshocarmel/multi-nginx
    - docker push jeshocarmel/multi-server
    - docker push jeshocarmel/multi-worker